
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CallLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CallLog
 * 
 */
export type CallLogModel = runtime.Types.Result.DefaultSelection<Prisma.$CallLogPayload>

export type AggregateCallLog = {
  _count: CallLogCountAggregateOutputType | null
  _avg: CallLogAvgAggregateOutputType | null
  _sum: CallLogSumAggregateOutputType | null
  _min: CallLogMinAggregateOutputType | null
  _max: CallLogMaxAggregateOutputType | null
}

export type CallLogAvgAggregateOutputType = {
  duration: number | null
}

export type CallLogSumAggregateOutputType = {
  duration: number | null
}

export type CallLogMinAggregateOutputType = {
  id: string | null
  leadId: string | null
  notes: string | null
  duration: number | null
  callTime: Date | null
  createdAt: Date | null
}

export type CallLogMaxAggregateOutputType = {
  id: string | null
  leadId: string | null
  notes: string | null
  duration: number | null
  callTime: Date | null
  createdAt: Date | null
}

export type CallLogCountAggregateOutputType = {
  id: number
  leadId: number
  notes: number
  duration: number
  callTime: number
  createdAt: number
  _all: number
}


export type CallLogAvgAggregateInputType = {
  duration?: true
}

export type CallLogSumAggregateInputType = {
  duration?: true
}

export type CallLogMinAggregateInputType = {
  id?: true
  leadId?: true
  notes?: true
  duration?: true
  callTime?: true
  createdAt?: true
}

export type CallLogMaxAggregateInputType = {
  id?: true
  leadId?: true
  notes?: true
  duration?: true
  callTime?: true
  createdAt?: true
}

export type CallLogCountAggregateInputType = {
  id?: true
  leadId?: true
  notes?: true
  duration?: true
  callTime?: true
  createdAt?: true
  _all?: true
}

export type CallLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CallLog to aggregate.
   */
  where?: Prisma.CallLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CallLogs to fetch.
   */
  orderBy?: Prisma.CallLogOrderByWithRelationInput | Prisma.CallLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CallLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CallLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CallLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CallLogs
  **/
  _count?: true | CallLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CallLogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CallLogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CallLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CallLogMaxAggregateInputType
}

export type GetCallLogAggregateType<T extends CallLogAggregateArgs> = {
      [P in keyof T & keyof AggregateCallLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCallLog[P]>
    : Prisma.GetScalarType<T[P], AggregateCallLog[P]>
}




export type CallLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CallLogWhereInput
  orderBy?: Prisma.CallLogOrderByWithAggregationInput | Prisma.CallLogOrderByWithAggregationInput[]
  by: Prisma.CallLogScalarFieldEnum[] | Prisma.CallLogScalarFieldEnum
  having?: Prisma.CallLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CallLogCountAggregateInputType | true
  _avg?: CallLogAvgAggregateInputType
  _sum?: CallLogSumAggregateInputType
  _min?: CallLogMinAggregateInputType
  _max?: CallLogMaxAggregateInputType
}

export type CallLogGroupByOutputType = {
  id: string
  leadId: string
  notes: string | null
  duration: number | null
  callTime: Date
  createdAt: Date
  _count: CallLogCountAggregateOutputType | null
  _avg: CallLogAvgAggregateOutputType | null
  _sum: CallLogSumAggregateOutputType | null
  _min: CallLogMinAggregateOutputType | null
  _max: CallLogMaxAggregateOutputType | null
}

type GetCallLogGroupByPayload<T extends CallLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CallLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CallLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CallLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CallLogGroupByOutputType[P]>
      }
    >
  >



export type CallLogWhereInput = {
  AND?: Prisma.CallLogWhereInput | Prisma.CallLogWhereInput[]
  OR?: Prisma.CallLogWhereInput[]
  NOT?: Prisma.CallLogWhereInput | Prisma.CallLogWhereInput[]
  id?: Prisma.StringFilter<"CallLog"> | string
  leadId?: Prisma.StringFilter<"CallLog"> | string
  notes?: Prisma.StringNullableFilter<"CallLog"> | string | null
  duration?: Prisma.IntNullableFilter<"CallLog"> | number | null
  callTime?: Prisma.DateTimeFilter<"CallLog"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"CallLog"> | Date | string
  lead?: Prisma.XOR<Prisma.LeadScalarRelationFilter, Prisma.LeadWhereInput>
}

export type CallLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  leadId?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  duration?: Prisma.SortOrderInput | Prisma.SortOrder
  callTime?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  lead?: Prisma.LeadOrderByWithRelationInput
}

export type CallLogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CallLogWhereInput | Prisma.CallLogWhereInput[]
  OR?: Prisma.CallLogWhereInput[]
  NOT?: Prisma.CallLogWhereInput | Prisma.CallLogWhereInput[]
  leadId?: Prisma.StringFilter<"CallLog"> | string
  notes?: Prisma.StringNullableFilter<"CallLog"> | string | null
  duration?: Prisma.IntNullableFilter<"CallLog"> | number | null
  callTime?: Prisma.DateTimeFilter<"CallLog"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"CallLog"> | Date | string
  lead?: Prisma.XOR<Prisma.LeadScalarRelationFilter, Prisma.LeadWhereInput>
}, "id">

export type CallLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  leadId?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  duration?: Prisma.SortOrderInput | Prisma.SortOrder
  callTime?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CallLogCountOrderByAggregateInput
  _avg?: Prisma.CallLogAvgOrderByAggregateInput
  _max?: Prisma.CallLogMaxOrderByAggregateInput
  _min?: Prisma.CallLogMinOrderByAggregateInput
  _sum?: Prisma.CallLogSumOrderByAggregateInput
}

export type CallLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.CallLogScalarWhereWithAggregatesInput | Prisma.CallLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.CallLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CallLogScalarWhereWithAggregatesInput | Prisma.CallLogScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CallLog"> | string
  leadId?: Prisma.StringWithAggregatesFilter<"CallLog"> | string
  notes?: Prisma.StringNullableWithAggregatesFilter<"CallLog"> | string | null
  duration?: Prisma.IntNullableWithAggregatesFilter<"CallLog"> | number | null
  callTime?: Prisma.DateTimeWithAggregatesFilter<"CallLog"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CallLog"> | Date | string
}

export type CallLogCreateInput = {
  id?: string
  notes?: string | null
  duration?: number | null
  callTime: Date | string
  createdAt?: Date | string
  lead: Prisma.LeadCreateNestedOneWithoutCallsInput
}

export type CallLogUncheckedCreateInput = {
  id?: string
  leadId: string
  notes?: string | null
  duration?: number | null
  callTime: Date | string
  createdAt?: Date | string
}

export type CallLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  callTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lead?: Prisma.LeadUpdateOneRequiredWithoutCallsNestedInput
}

export type CallLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leadId?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  callTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CallLogCreateManyInput = {
  id?: string
  leadId: string
  notes?: string | null
  duration?: number | null
  callTime: Date | string
  createdAt?: Date | string
}

export type CallLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  callTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CallLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  leadId?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  callTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CallLogListRelationFilter = {
  every?: Prisma.CallLogWhereInput
  some?: Prisma.CallLogWhereInput
  none?: Prisma.CallLogWhereInput
}

export type CallLogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CallLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  leadId?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  callTime?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CallLogAvgOrderByAggregateInput = {
  duration?: Prisma.SortOrder
}

export type CallLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  leadId?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  callTime?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CallLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  leadId?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  callTime?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CallLogSumOrderByAggregateInput = {
  duration?: Prisma.SortOrder
}

export type CallLogCreateNestedManyWithoutLeadInput = {
  create?: Prisma.XOR<Prisma.CallLogCreateWithoutLeadInput, Prisma.CallLogUncheckedCreateWithoutLeadInput> | Prisma.CallLogCreateWithoutLeadInput[] | Prisma.CallLogUncheckedCreateWithoutLeadInput[]
  connectOrCreate?: Prisma.CallLogCreateOrConnectWithoutLeadInput | Prisma.CallLogCreateOrConnectWithoutLeadInput[]
  createMany?: Prisma.CallLogCreateManyLeadInputEnvelope
  connect?: Prisma.CallLogWhereUniqueInput | Prisma.CallLogWhereUniqueInput[]
}

export type CallLogUncheckedCreateNestedManyWithoutLeadInput = {
  create?: Prisma.XOR<Prisma.CallLogCreateWithoutLeadInput, Prisma.CallLogUncheckedCreateWithoutLeadInput> | Prisma.CallLogCreateWithoutLeadInput[] | Prisma.CallLogUncheckedCreateWithoutLeadInput[]
  connectOrCreate?: Prisma.CallLogCreateOrConnectWithoutLeadInput | Prisma.CallLogCreateOrConnectWithoutLeadInput[]
  createMany?: Prisma.CallLogCreateManyLeadInputEnvelope
  connect?: Prisma.CallLogWhereUniqueInput | Prisma.CallLogWhereUniqueInput[]
}

export type CallLogUpdateManyWithoutLeadNestedInput = {
  create?: Prisma.XOR<Prisma.CallLogCreateWithoutLeadInput, Prisma.CallLogUncheckedCreateWithoutLeadInput> | Prisma.CallLogCreateWithoutLeadInput[] | Prisma.CallLogUncheckedCreateWithoutLeadInput[]
  connectOrCreate?: Prisma.CallLogCreateOrConnectWithoutLeadInput | Prisma.CallLogCreateOrConnectWithoutLeadInput[]
  upsert?: Prisma.CallLogUpsertWithWhereUniqueWithoutLeadInput | Prisma.CallLogUpsertWithWhereUniqueWithoutLeadInput[]
  createMany?: Prisma.CallLogCreateManyLeadInputEnvelope
  set?: Prisma.CallLogWhereUniqueInput | Prisma.CallLogWhereUniqueInput[]
  disconnect?: Prisma.CallLogWhereUniqueInput | Prisma.CallLogWhereUniqueInput[]
  delete?: Prisma.CallLogWhereUniqueInput | Prisma.CallLogWhereUniqueInput[]
  connect?: Prisma.CallLogWhereUniqueInput | Prisma.CallLogWhereUniqueInput[]
  update?: Prisma.CallLogUpdateWithWhereUniqueWithoutLeadInput | Prisma.CallLogUpdateWithWhereUniqueWithoutLeadInput[]
  updateMany?: Prisma.CallLogUpdateManyWithWhereWithoutLeadInput | Prisma.CallLogUpdateManyWithWhereWithoutLeadInput[]
  deleteMany?: Prisma.CallLogScalarWhereInput | Prisma.CallLogScalarWhereInput[]
}

export type CallLogUncheckedUpdateManyWithoutLeadNestedInput = {
  create?: Prisma.XOR<Prisma.CallLogCreateWithoutLeadInput, Prisma.CallLogUncheckedCreateWithoutLeadInput> | Prisma.CallLogCreateWithoutLeadInput[] | Prisma.CallLogUncheckedCreateWithoutLeadInput[]
  connectOrCreate?: Prisma.CallLogCreateOrConnectWithoutLeadInput | Prisma.CallLogCreateOrConnectWithoutLeadInput[]
  upsert?: Prisma.CallLogUpsertWithWhereUniqueWithoutLeadInput | Prisma.CallLogUpsertWithWhereUniqueWithoutLeadInput[]
  createMany?: Prisma.CallLogCreateManyLeadInputEnvelope
  set?: Prisma.CallLogWhereUniqueInput | Prisma.CallLogWhereUniqueInput[]
  disconnect?: Prisma.CallLogWhereUniqueInput | Prisma.CallLogWhereUniqueInput[]
  delete?: Prisma.CallLogWhereUniqueInput | Prisma.CallLogWhereUniqueInput[]
  connect?: Prisma.CallLogWhereUniqueInput | Prisma.CallLogWhereUniqueInput[]
  update?: Prisma.CallLogUpdateWithWhereUniqueWithoutLeadInput | Prisma.CallLogUpdateWithWhereUniqueWithoutLeadInput[]
  updateMany?: Prisma.CallLogUpdateManyWithWhereWithoutLeadInput | Prisma.CallLogUpdateManyWithWhereWithoutLeadInput[]
  deleteMany?: Prisma.CallLogScalarWhereInput | Prisma.CallLogScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type CallLogCreateWithoutLeadInput = {
  id?: string
  notes?: string | null
  duration?: number | null
  callTime: Date | string
  createdAt?: Date | string
}

export type CallLogUncheckedCreateWithoutLeadInput = {
  id?: string
  notes?: string | null
  duration?: number | null
  callTime: Date | string
  createdAt?: Date | string
}

export type CallLogCreateOrConnectWithoutLeadInput = {
  where: Prisma.CallLogWhereUniqueInput
  create: Prisma.XOR<Prisma.CallLogCreateWithoutLeadInput, Prisma.CallLogUncheckedCreateWithoutLeadInput>
}

export type CallLogCreateManyLeadInputEnvelope = {
  data: Prisma.CallLogCreateManyLeadInput | Prisma.CallLogCreateManyLeadInput[]
}

export type CallLogUpsertWithWhereUniqueWithoutLeadInput = {
  where: Prisma.CallLogWhereUniqueInput
  update: Prisma.XOR<Prisma.CallLogUpdateWithoutLeadInput, Prisma.CallLogUncheckedUpdateWithoutLeadInput>
  create: Prisma.XOR<Prisma.CallLogCreateWithoutLeadInput, Prisma.CallLogUncheckedCreateWithoutLeadInput>
}

export type CallLogUpdateWithWhereUniqueWithoutLeadInput = {
  where: Prisma.CallLogWhereUniqueInput
  data: Prisma.XOR<Prisma.CallLogUpdateWithoutLeadInput, Prisma.CallLogUncheckedUpdateWithoutLeadInput>
}

export type CallLogUpdateManyWithWhereWithoutLeadInput = {
  where: Prisma.CallLogScalarWhereInput
  data: Prisma.XOR<Prisma.CallLogUpdateManyMutationInput, Prisma.CallLogUncheckedUpdateManyWithoutLeadInput>
}

export type CallLogScalarWhereInput = {
  AND?: Prisma.CallLogScalarWhereInput | Prisma.CallLogScalarWhereInput[]
  OR?: Prisma.CallLogScalarWhereInput[]
  NOT?: Prisma.CallLogScalarWhereInput | Prisma.CallLogScalarWhereInput[]
  id?: Prisma.StringFilter<"CallLog"> | string
  leadId?: Prisma.StringFilter<"CallLog"> | string
  notes?: Prisma.StringNullableFilter<"CallLog"> | string | null
  duration?: Prisma.IntNullableFilter<"CallLog"> | number | null
  callTime?: Prisma.DateTimeFilter<"CallLog"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"CallLog"> | Date | string
}

export type CallLogCreateManyLeadInput = {
  id?: string
  notes?: string | null
  duration?: number | null
  callTime: Date | string
  createdAt?: Date | string
}

export type CallLogUpdateWithoutLeadInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  callTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CallLogUncheckedUpdateWithoutLeadInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  callTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CallLogUncheckedUpdateManyWithoutLeadInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  callTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CallLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  leadId?: boolean
  notes?: boolean
  duration?: boolean
  callTime?: boolean
  createdAt?: boolean
  lead?: boolean | Prisma.LeadDefaultArgs<ExtArgs>
}, ExtArgs["result"]["callLog"]>

export type CallLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  leadId?: boolean
  notes?: boolean
  duration?: boolean
  callTime?: boolean
  createdAt?: boolean
  lead?: boolean | Prisma.LeadDefaultArgs<ExtArgs>
}, ExtArgs["result"]["callLog"]>

export type CallLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  leadId?: boolean
  notes?: boolean
  duration?: boolean
  callTime?: boolean
  createdAt?: boolean
  lead?: boolean | Prisma.LeadDefaultArgs<ExtArgs>
}, ExtArgs["result"]["callLog"]>

export type CallLogSelectScalar = {
  id?: boolean
  leadId?: boolean
  notes?: boolean
  duration?: boolean
  callTime?: boolean
  createdAt?: boolean
}

export type CallLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "leadId" | "notes" | "duration" | "callTime" | "createdAt", ExtArgs["result"]["callLog"]>
export type CallLogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lead?: boolean | Prisma.LeadDefaultArgs<ExtArgs>
}
export type CallLogIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lead?: boolean | Prisma.LeadDefaultArgs<ExtArgs>
}
export type CallLogIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lead?: boolean | Prisma.LeadDefaultArgs<ExtArgs>
}

export type $CallLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CallLog"
  objects: {
    lead: Prisma.$LeadPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    leadId: string
    notes: string | null
    duration: number | null
    callTime: Date
    createdAt: Date
  }, ExtArgs["result"]["callLog"]>
  composites: {}
}

export type CallLogGetPayload<S extends boolean | null | undefined | CallLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CallLogPayload, S>

export type CallLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CallLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CallLogCountAggregateInputType | true
  }

export interface CallLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CallLog'], meta: { name: 'CallLog' } }
  /**
   * Find zero or one CallLog that matches the filter.
   * @param {CallLogFindUniqueArgs} args - Arguments to find a CallLog
   * @example
   * // Get one CallLog
   * const callLog = await prisma.callLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CallLogFindUniqueArgs>(args: Prisma.SelectSubset<T, CallLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CallLogClient<runtime.Types.Result.GetResult<Prisma.$CallLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CallLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CallLogFindUniqueOrThrowArgs} args - Arguments to find a CallLog
   * @example
   * // Get one CallLog
   * const callLog = await prisma.callLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CallLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CallLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CallLogClient<runtime.Types.Result.GetResult<Prisma.$CallLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CallLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallLogFindFirstArgs} args - Arguments to find a CallLog
   * @example
   * // Get one CallLog
   * const callLog = await prisma.callLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CallLogFindFirstArgs>(args?: Prisma.SelectSubset<T, CallLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__CallLogClient<runtime.Types.Result.GetResult<Prisma.$CallLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CallLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallLogFindFirstOrThrowArgs} args - Arguments to find a CallLog
   * @example
   * // Get one CallLog
   * const callLog = await prisma.callLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CallLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CallLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CallLogClient<runtime.Types.Result.GetResult<Prisma.$CallLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CallLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CallLogs
   * const callLogs = await prisma.callLog.findMany()
   * 
   * // Get first 10 CallLogs
   * const callLogs = await prisma.callLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const callLogWithIdOnly = await prisma.callLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CallLogFindManyArgs>(args?: Prisma.SelectSubset<T, CallLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CallLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CallLog.
   * @param {CallLogCreateArgs} args - Arguments to create a CallLog.
   * @example
   * // Create one CallLog
   * const CallLog = await prisma.callLog.create({
   *   data: {
   *     // ... data to create a CallLog
   *   }
   * })
   * 
   */
  create<T extends CallLogCreateArgs>(args: Prisma.SelectSubset<T, CallLogCreateArgs<ExtArgs>>): Prisma.Prisma__CallLogClient<runtime.Types.Result.GetResult<Prisma.$CallLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CallLogs.
   * @param {CallLogCreateManyArgs} args - Arguments to create many CallLogs.
   * @example
   * // Create many CallLogs
   * const callLog = await prisma.callLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CallLogCreateManyArgs>(args?: Prisma.SelectSubset<T, CallLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CallLogs and returns the data saved in the database.
   * @param {CallLogCreateManyAndReturnArgs} args - Arguments to create many CallLogs.
   * @example
   * // Create many CallLogs
   * const callLog = await prisma.callLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CallLogs and only return the `id`
   * const callLogWithIdOnly = await prisma.callLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CallLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CallLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CallLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CallLog.
   * @param {CallLogDeleteArgs} args - Arguments to delete one CallLog.
   * @example
   * // Delete one CallLog
   * const CallLog = await prisma.callLog.delete({
   *   where: {
   *     // ... filter to delete one CallLog
   *   }
   * })
   * 
   */
  delete<T extends CallLogDeleteArgs>(args: Prisma.SelectSubset<T, CallLogDeleteArgs<ExtArgs>>): Prisma.Prisma__CallLogClient<runtime.Types.Result.GetResult<Prisma.$CallLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CallLog.
   * @param {CallLogUpdateArgs} args - Arguments to update one CallLog.
   * @example
   * // Update one CallLog
   * const callLog = await prisma.callLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CallLogUpdateArgs>(args: Prisma.SelectSubset<T, CallLogUpdateArgs<ExtArgs>>): Prisma.Prisma__CallLogClient<runtime.Types.Result.GetResult<Prisma.$CallLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CallLogs.
   * @param {CallLogDeleteManyArgs} args - Arguments to filter CallLogs to delete.
   * @example
   * // Delete a few CallLogs
   * const { count } = await prisma.callLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CallLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, CallLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CallLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CallLogs
   * const callLog = await prisma.callLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CallLogUpdateManyArgs>(args: Prisma.SelectSubset<T, CallLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CallLogs and returns the data updated in the database.
   * @param {CallLogUpdateManyAndReturnArgs} args - Arguments to update many CallLogs.
   * @example
   * // Update many CallLogs
   * const callLog = await prisma.callLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CallLogs and only return the `id`
   * const callLogWithIdOnly = await prisma.callLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CallLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CallLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CallLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CallLog.
   * @param {CallLogUpsertArgs} args - Arguments to update or create a CallLog.
   * @example
   * // Update or create a CallLog
   * const callLog = await prisma.callLog.upsert({
   *   create: {
   *     // ... data to create a CallLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CallLog we want to update
   *   }
   * })
   */
  upsert<T extends CallLogUpsertArgs>(args: Prisma.SelectSubset<T, CallLogUpsertArgs<ExtArgs>>): Prisma.Prisma__CallLogClient<runtime.Types.Result.GetResult<Prisma.$CallLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CallLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallLogCountArgs} args - Arguments to filter CallLogs to count.
   * @example
   * // Count the number of CallLogs
   * const count = await prisma.callLog.count({
   *   where: {
   *     // ... the filter for the CallLogs we want to count
   *   }
   * })
  **/
  count<T extends CallLogCountArgs>(
    args?: Prisma.Subset<T, CallLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CallLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CallLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CallLogAggregateArgs>(args: Prisma.Subset<T, CallLogAggregateArgs>): Prisma.PrismaPromise<GetCallLogAggregateType<T>>

  /**
   * Group by CallLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CallLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CallLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CallLogGroupByArgs['orderBy'] }
      : { orderBy?: CallLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CallLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCallLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CallLog model
 */
readonly fields: CallLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CallLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CallLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  lead<T extends Prisma.LeadDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LeadDefaultArgs<ExtArgs>>): Prisma.Prisma__LeadClient<runtime.Types.Result.GetResult<Prisma.$LeadPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CallLog model
 */
export interface CallLogFieldRefs {
  readonly id: Prisma.FieldRef<"CallLog", 'String'>
  readonly leadId: Prisma.FieldRef<"CallLog", 'String'>
  readonly notes: Prisma.FieldRef<"CallLog", 'String'>
  readonly duration: Prisma.FieldRef<"CallLog", 'Int'>
  readonly callTime: Prisma.FieldRef<"CallLog", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"CallLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CallLog findUnique
 */
export type CallLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallLog
   */
  select?: Prisma.CallLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallLog
   */
  omit?: Prisma.CallLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallLogInclude<ExtArgs> | null
  /**
   * Filter, which CallLog to fetch.
   */
  where: Prisma.CallLogWhereUniqueInput
}

/**
 * CallLog findUniqueOrThrow
 */
export type CallLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallLog
   */
  select?: Prisma.CallLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallLog
   */
  omit?: Prisma.CallLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallLogInclude<ExtArgs> | null
  /**
   * Filter, which CallLog to fetch.
   */
  where: Prisma.CallLogWhereUniqueInput
}

/**
 * CallLog findFirst
 */
export type CallLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallLog
   */
  select?: Prisma.CallLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallLog
   */
  omit?: Prisma.CallLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallLogInclude<ExtArgs> | null
  /**
   * Filter, which CallLog to fetch.
   */
  where?: Prisma.CallLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CallLogs to fetch.
   */
  orderBy?: Prisma.CallLogOrderByWithRelationInput | Prisma.CallLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CallLogs.
   */
  cursor?: Prisma.CallLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CallLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CallLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CallLogs.
   */
  distinct?: Prisma.CallLogScalarFieldEnum | Prisma.CallLogScalarFieldEnum[]
}

/**
 * CallLog findFirstOrThrow
 */
export type CallLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallLog
   */
  select?: Prisma.CallLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallLog
   */
  omit?: Prisma.CallLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallLogInclude<ExtArgs> | null
  /**
   * Filter, which CallLog to fetch.
   */
  where?: Prisma.CallLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CallLogs to fetch.
   */
  orderBy?: Prisma.CallLogOrderByWithRelationInput | Prisma.CallLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CallLogs.
   */
  cursor?: Prisma.CallLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CallLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CallLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CallLogs.
   */
  distinct?: Prisma.CallLogScalarFieldEnum | Prisma.CallLogScalarFieldEnum[]
}

/**
 * CallLog findMany
 */
export type CallLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallLog
   */
  select?: Prisma.CallLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallLog
   */
  omit?: Prisma.CallLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallLogInclude<ExtArgs> | null
  /**
   * Filter, which CallLogs to fetch.
   */
  where?: Prisma.CallLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CallLogs to fetch.
   */
  orderBy?: Prisma.CallLogOrderByWithRelationInput | Prisma.CallLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CallLogs.
   */
  cursor?: Prisma.CallLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CallLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CallLogs.
   */
  skip?: number
  distinct?: Prisma.CallLogScalarFieldEnum | Prisma.CallLogScalarFieldEnum[]
}

/**
 * CallLog create
 */
export type CallLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallLog
   */
  select?: Prisma.CallLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallLog
   */
  omit?: Prisma.CallLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallLogInclude<ExtArgs> | null
  /**
   * The data needed to create a CallLog.
   */
  data: Prisma.XOR<Prisma.CallLogCreateInput, Prisma.CallLogUncheckedCreateInput>
}

/**
 * CallLog createMany
 */
export type CallLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CallLogs.
   */
  data: Prisma.CallLogCreateManyInput | Prisma.CallLogCreateManyInput[]
}

/**
 * CallLog createManyAndReturn
 */
export type CallLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallLog
   */
  select?: Prisma.CallLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CallLog
   */
  omit?: Prisma.CallLogOmit<ExtArgs> | null
  /**
   * The data used to create many CallLogs.
   */
  data: Prisma.CallLogCreateManyInput | Prisma.CallLogCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallLogIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CallLog update
 */
export type CallLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallLog
   */
  select?: Prisma.CallLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallLog
   */
  omit?: Prisma.CallLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallLogInclude<ExtArgs> | null
  /**
   * The data needed to update a CallLog.
   */
  data: Prisma.XOR<Prisma.CallLogUpdateInput, Prisma.CallLogUncheckedUpdateInput>
  /**
   * Choose, which CallLog to update.
   */
  where: Prisma.CallLogWhereUniqueInput
}

/**
 * CallLog updateMany
 */
export type CallLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CallLogs.
   */
  data: Prisma.XOR<Prisma.CallLogUpdateManyMutationInput, Prisma.CallLogUncheckedUpdateManyInput>
  /**
   * Filter which CallLogs to update
   */
  where?: Prisma.CallLogWhereInput
  /**
   * Limit how many CallLogs to update.
   */
  limit?: number
}

/**
 * CallLog updateManyAndReturn
 */
export type CallLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallLog
   */
  select?: Prisma.CallLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CallLog
   */
  omit?: Prisma.CallLogOmit<ExtArgs> | null
  /**
   * The data used to update CallLogs.
   */
  data: Prisma.XOR<Prisma.CallLogUpdateManyMutationInput, Prisma.CallLogUncheckedUpdateManyInput>
  /**
   * Filter which CallLogs to update
   */
  where?: Prisma.CallLogWhereInput
  /**
   * Limit how many CallLogs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallLogIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CallLog upsert
 */
export type CallLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallLog
   */
  select?: Prisma.CallLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallLog
   */
  omit?: Prisma.CallLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallLogInclude<ExtArgs> | null
  /**
   * The filter to search for the CallLog to update in case it exists.
   */
  where: Prisma.CallLogWhereUniqueInput
  /**
   * In case the CallLog found by the `where` argument doesn't exist, create a new CallLog with this data.
   */
  create: Prisma.XOR<Prisma.CallLogCreateInput, Prisma.CallLogUncheckedCreateInput>
  /**
   * In case the CallLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CallLogUpdateInput, Prisma.CallLogUncheckedUpdateInput>
}

/**
 * CallLog delete
 */
export type CallLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallLog
   */
  select?: Prisma.CallLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallLog
   */
  omit?: Prisma.CallLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallLogInclude<ExtArgs> | null
  /**
   * Filter which CallLog to delete.
   */
  where: Prisma.CallLogWhereUniqueInput
}

/**
 * CallLog deleteMany
 */
export type CallLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CallLogs to delete
   */
  where?: Prisma.CallLogWhereInput
  /**
   * Limit how many CallLogs to delete.
   */
  limit?: number
}

/**
 * CallLog without action
 */
export type CallLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CallLog
   */
  select?: Prisma.CallLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CallLog
   */
  omit?: Prisma.CallLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CallLogInclude<ExtArgs> | null
}
