
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Stage'
export type * from './models/Lead'
export type * from './models/CustomField'
export type * from './models/Note'
export type * from './models/Email'
export type * from './models/CallLog'
export type * from './models/Activity'
export type * from './models/PaymentLink'
export type * from './commonInputTypes'